pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}

rootProject.name = 'RncustomergluExample'

// Apply React Native native modules
apply from: file("../node_modules/@react-native-community/cli-platform-android/native_modules.gradle")
applyNativeModulesSettingsGradle(settings)

include ':app'

// Include React Native Gradle Plugin
includeBuild('../node_modules/@react-native/gradle-plugin')