# Add at the top of your Podfile
source 'https://github.com/CocoaPods/Specs.git'
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

# Hermes configuration
$RNHermesLocation = "../node_modules/react-native/sdks/hermes-engine/destroot"
$static_framework = []

# Add Hermes as a static framework
if ENV['RCT_NEW_ARCH_ENABLED'] == '1'
  $static_framework += ['hermes-engine']
end

platform :ios, '15.0'
prepare_react_native_project!

# Flags change depending on the env values.
ENV['RCT_NEW_ARCH_ENABLED'] = '1'
install! 'cocoapods', :deterministic_uuids => false
use_frameworks! :linkage => :static
pod 'Firebase/Messaging'

$RNFirebaseAsStaticFramework = true

target 'RncustomergluExample' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    :hermes_enabled => true,
    :fabric_enabled => true,
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )
    
  # Add CustomerGlu SDK
  pod 'react-native-customerglu', :path => '../node_modules/react-native-customerglu' 
   
  # Third-party dependencies
  pod 'RNCAsyncStorage', :path => '../node_modules/@react-native-async-storage/async-storage'
  pod 'RNFBApp', :path => '../node_modules/@react-native-firebase/app'
  pod 'RNFBMessaging', :path => '../node_modules/@react-native-firebase/messaging'
  
  post_install do |installer|
    # Ensure pods also build with new architecture
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        # Initialize preprocessor definitions
        config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)']
        
        # Architecture settings for all targets
        config.build_settings['ONLY_ACTIVE_ARCH'] = 'NO'
        
        # Enable all available hardening flags
        config.build_settings['DEAD_CODE_STRIPPING'] = 'YES'
        config.build_settings['CLANG_WARN_DOCUMENTATION_COMMENTS'] = 'YES'
        config.build_settings['CLANG_WARN_QUOTED_INCLUDE_IN_FRAMEWORK_HEADER'] = 'YES'
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
        
        # Swift specific settings
        if target.respond_to?(:product_type) && target.product_type == "com.apple.product-type.framework"
          config.build_settings['SWIFT_VERSION'] = '5.0'
          config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
        end

        # Architecture settings for simulator
        if config.build_settings['SDKROOT'] == 'iphonesimulator'
          config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'arm64'
          config.build_settings['ARCHS[sdk=iphonesimulator*]'] = 'x86_64'
        end
        
        # C++ Standard Library configuration
        config.build_settings['CLANG_CXX_LANGUAGE_STANDARD'] = 'c++17'
        config.build_settings['CLANG_CXX_LIBRARY'] = 'libc++'
        config.build_settings['HEADER_SEARCH_PATHS'] = '$(inherited) "$(PODS_ROOT)/boost" "$(PODS_ROOT)/boost-for-react-native" "$(PODS_ROOT)/RCT-Folly"'
        
        # Additional settings for Hermes
        if target.name == "hermes-engine"
          config.build_settings['ONLY_ACTIVE_ARCH'] = 'NO'
        end
      end

      # Static frameworks
      if $static_framework.include?(target.name)
        target.build_configurations.each do |config|
          config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
          config.build_settings['SWIFT_VERSION'] = '5.0'
        end
      end
      
      # CustomerGlu specific settings
      if target.name == "CustomerGlu" || target.name == "react-native-customerglu"
        target.build_configurations.each do |config|
          config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
          config.build_settings['SWIFT_VERSION'] = '5.0'
          config.build_settings['ENABLE_BITCODE'] = 'NO'
          config.build_settings['SWIFT_OPTIMIZATION_LEVEL'] = '-Onone'
        end
      end
    end

    react_native_post_install(
      installer,
      config[:reactNativePath]
    )

    # Final Hermes configuration
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        if target.name == "hermes-engine"
          config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
          config.build_settings['HERMES_ENGINE_PATH'] = File.expand_path("../node_modules/react-native/sdks/hermes-engine", __dir__)
        end
      end
    end
  end 
end
