require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '15.0'
install! 'cocoapods', :deterministic_uuids => false
use_frameworks! :linkage => :static
pod 'Firebase/Messaging'

  # use_frameworks!
  $RNFirebaseAsStaticFramework = true

target 'RncustomergluExample' do
  config = use_native_modules!

   # Flags change depending on the env values.
  flags = get_default_flags()

  use_react_native!(:path => config["reactNativePath"],
  :hermes_enabled => flags[:hermes_enabled],
    :fabric_enabled => flags[:fabric_enabled],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )
    
# -------- ADD this library to link with podspac --------------

  pod 'react-native-customerglu', :path => '../..'
   
 pod 'RNCAsyncStorage', :path => '../node_modules/@react-native-async-storage/async-storage'
  pod 'RNFBApp', :path => '../node_modules/@react-native-firebase/app'
  pod 'RNFBMessaging', :path => '../node_modules/@react-native-firebase/messaging'
  # pod "react-native-broadcast-manager", :path => '../../node_modules/@applicaster/react-native-broadcast-manager'
  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  # use_flipper!()
  post_install do |installer|
    react_native_post_install(installer)
    __apply_Xcode_12_5_M1_post_install_workaround(installer)
  end
end
