# Add at the top of your Podfile
source 'https://github.com/CocoaPods/Specs.git'

require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '15.0'
prepare_react_native_project!

# Flags change depending on the env values.
ENV['RCT_NEW_ARCH_ENABLED'] = '1'
install! 'cocoapods', :deterministic_uuids => false

# Configure frameworks
$RNFirebaseAsStaticFramework = true

target 'RncustomergluExample' do
  config = use_native_modules!

  # React Native
  use_react_native!(
    :path => config[:reactNativePath],
    :hermes_enabled => true,
    :fabric_enabled => true,
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  # Firebase
  pod 'Firebase/Messaging'
    
  # Add CustomerGlu SDK
  pod 'react-native-customerglu', :path => '../..'
   
  # Third-party dependencies
  pod 'RNCAsyncStorage', :path => '../node_modules/@react-native-async-storage/async-storage'
  pod 'RNFBApp', :path => '../node_modules/@react-native-firebase/app'
  pod 'RNFBMessaging', :path => '../node_modules/@react-native-firebase/messaging'
  
  post_install do |installer|
    # Ensure pods also build with new architecture
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)']
        config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] << 'RCT_NEW_ARCH_ENABLED=1'
        
        # Enable all available hardening flags
        config.build_settings['DEAD_CODE_STRIPPING'] = 'YES'
        config.build_settings['CLANG_WARN_DOCUMENTATION_COMMENTS'] = 'YES'
        config.build_settings['CLANG_WARN_QUOTED_INCLUDE_IN_FRAMEWORK_HEADER'] = 'YES'
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
        
        # Fix for Swift bridging
        config.build_settings['SWIFT_VERSION'] = '5.0'
        config.build_settings['SWIFT_OBJC_BRIDGING_HEADER'] = '$(SRCROOT)/RncustomergluExample-Bridging-Header.h'
        config.build_settings['SWIFT_OBJC_INTERFACE_HEADER_NAME'] = 'RncustomergluExample-Swift.h'
      end
    end

    react_native_post_install(installer)
    
    # Apply Mac M1 Apple Silicon fixes
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = "arm64"
      end
    end
  end
end
