import { NativeEventEmitter } from 'react-native';
declare type CgnativeuiProps = {
    bannerId: string;
};
export declare const BannerWidget: import("react-native").HostComponent<CgnativeuiProps> | (() => never);
export declare function RegisterDevice(userdata: Object): Promise<number>;
export declare function dataClear(): Promise<number>;
export declare function sendData(obj: Object): Promise<number>;
export declare function openWallet(): Promise<number>;
export declare function loadCampaignIdBy(id: String): Promise<number>;
export declare function enableAnalytic(b: Boolean): Promise<number>;
export declare function sendEventToJs(b: NativeEventEmitter): Promise<number>;
export declare function disableGluSdk(a: Boolean): Promise<number>;
export declare function configureLoaderColour(colr: String): Promise<number>;
export declare function enablePrecaching(): Promise<number>;
export declare function gluSDKDebuggingMode(b: Boolean): Promise<number>;
export declare function enableEntryPoints(b: boolean): Promise<number>;
export declare function closeWebView(b: Boolean): Promise<number>;
export declare function isFcmApn(id: Boolean): Promise<number>;
export declare function configureSafeArea(obj: Object): Promise<number>;
export declare function SetDefaultBannerImage(url: String): Promise<number>;
export declare function UpdateProfile(obj: Object): Promise<number>;
export declare function DisplayCustomerGluNotification(): Promise<number>;
export declare function CGApplication(): Promise<number>;
export declare function DisplayBackGroundNotification(obj: Object): Promise<number>;
export declare function GetRefferalId(url: String): Promise<number>;
export declare function LoadAllCampagins(): Promise<number>;
export declare function LoadCampaginsByFilter(obj: Object): Promise<number>;
export declare function SetCurrentClassName(clname: String): Promise<number>;
export declare function OpenWalletWithUrl(url: String): Promise<number>;
export declare function configureWhiteListedDomains(arr: Array<String>): Promise<number>;
export declare function configureDomainCodeMsg(obj: Object): Promise<number>;
export declare function setApnFcmToken(a: string, b: String): Promise<number>;
export declare function getBannerHeight(): Promise<number>;
export {};
