import { NativeEventEmitter } from 'react-native';
declare type CgnativeuiProps = {
    bannerId: string;
};
export declare const BannerWidget: import("react-native").HostComponent<CgnativeuiProps> | (() => never);
export declare function registerEx(): Promise<number>;
export declare function RegisterDevice(userdata: Object): Promise<number>;
export declare function dataClearEx(): Promise<number>;
export declare function sendDataEX(obj: Object): Promise<number>;
export declare function openWalletEx(): Promise<number>;
export declare function loadCampaignIdByEx(id: String): Promise<number>;
export declare function enableAnalyticEx(b: Boolean): Promise<number>;
export declare function sendEventToJsEx(b: NativeEventEmitter): Promise<number>;
export declare function disableGluSdkEx(a: Boolean): Promise<number>;
export declare function configureLoaderColourEx(colr: String): Promise<number>;
export declare function enablePrecachingEx(): Promise<number>;
export declare function gluSDKDebuggingModeEx(b: Boolean): Promise<number>;
export declare function enableEntryPointsEx(b: boolean): Promise<number>;
export declare function closeWebViewEx(b: Boolean): Promise<number>;
export declare function isFcmApnEx(id: Boolean): Promise<number>;
export declare function configureSafeAreaEx(obj: Object): Promise<number>;
export declare function SetDefaultBannerImageEx(url: String): Promise<number>;
export declare function UpdateProfileEx(): Promise<number>;
export declare function UpdateProfileExAndroid(userdata: Object): Promise<number>;
export declare function DisplayCustomerGluNotificationEx(): Promise<number>;
export declare function CGApplicationEx(): Promise<number>;
export declare function DisplayBackGroundNotificationEx(): Promise<number>;
export declare function GetRefferalIdEx(url: String): Promise<number>;
export declare function LoadAllCampaginsEx(): Promise<number>;
export declare function LoadCampaginsByFilterEx(obj: Object): Promise<number>;
export declare function SetCurrentClassNameEx(clName: String): Promise<number>;
export declare function OpenWalletWithUrlEx(url: String): Promise<number>;
export declare function configureWhiteListedDomainsEx(): Promise<number>;
export declare function configureDomainCodeMsgEx(): Promise<number>;
export {};
